pulselake:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5433') | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'pulselake') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'pulselake') }}"
      schema: analytics
      threads: 4
